//src/app/api/user/route.ts
import { NextRequest, NextResponse } from 'next/server';
import { supabase } from '@/lib/supabase';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();

    // Validate required fields
    if (!body.first_name || !body.age || !body.grade_level) {
      return NextResponse.json(
        { error: 'first_name, age, and grade_level are required' },
        { status: 400 }
      );
    }

    // Create new user object - let database generate user_id
    const newUser = {
      // Remove user_id - let the database generate it
      username: body.username || `student_${Date.now()}`,
      first_name: body.first_name,
      last_name: body.last_name || '',
      age: body.age,
      grade_level: body.grade_level,
      education_board: body.education_board || 'OTHER',
      preferred_language: body.preferred_language || 'en',
      timezone: body.timezone || 'Asia/Kolkata',
      facts_opt_in: body.facts_opt_in !== undefined ? body.facts_opt_in : true,
      onboarding_completed: body.onboarding_completed !== undefined ? body.onboarding_completed : true,
      is_active: true
      // created_at will be auto-generated by the database
    };

    // Store user in database
    const { data: createdUser, error } = await supabase
      .from('users')
      .insert(newUser)
      .select()
      .single();

    if (error) {
      console.error('Supabase error creating user:', error);
      return NextResponse.json(
        { error: error.message || 'Failed to create user' },
        { status: 500 }
      );
    }

    return NextResponse.json(createdUser, { status: 201 });

  } catch (error) {
    console.error('User creation error:', error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Internal server error' },
      { status: 500 }
    );
  }
}

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const userId = searchParams.get('user_id');
    const username = searchParams.get('username');

    if (!userId && !username) {
      return NextResponse.json(
        { error: 'user_id or username is required' },
        { status: 400 }
      );
    }

    let query = supabase.from('users').select('*');

    if (userId) {
      query = query.eq('user_id', userId);
    } else if (username) {
      query = query.eq('username', username);
    }

    const { data: user, error } = await query.single();

    if (error || !user) {
      return NextResponse.json(
        { error: 'User not found' },
        { status: 404 }
      );
    }

    return NextResponse.json(user);

  } catch (error) {
    console.error('User fetch error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

export async function PATCH(request: NextRequest) {
  try {
    const body = await request.json();
    const { user_id, ...updates } = body;

    if (!user_id) {
      return NextResponse.json(
        { error: 'user_id is required' },
        { status: 400 }
      );
    }

    // Check if user exists
    const { data: existingUser, error: fetchError } = await supabase
      .from('users')
      .select('*')
      .eq('user_id', user_id)
      .single();

    if (fetchError || !existingUser) {
      return NextResponse.json(
        { error: 'User not found' },
        { status: 404 }
      );
    }

    // Update user
    const { data: updatedUser, error: updateError } = await supabase
      .from('users')
      .update(updates)
      .eq('user_id', user_id)
      .select()
      .single();

    if (updateError) {
      throw updateError;
    }

    return NextResponse.json(updatedUser);

  } catch (error) {
    console.error('User update error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}